version: '3'

services:
  mapnik:
    build: .
    volumes:
       - ..:/var/OpenArdenneMap
  db:
    image: mdillon/postgis
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=osmpg
      - POSTGRES_DB=osmpg_db
