version: '3'

services:
  mapnik:
    build: .
    volumes:
       - ..:/var/OpenArdenneMap
  db:
    image: postgis/postgis:13-3.2-alpine
    ports:
      - "5439:5432"
    environment:
      - POSTGRES_USER=osmpg
      - POSTGRES_DB=osmpg_db
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./.data/db/data:/var/lib/postgresql/data"